on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-20.04 # TODO: need add self-hosted 
    strategy:
      fail-fast: false
      # max-parallel: 4
      matrix:
        board: [ stm32mp157a-sodimm2-mx, stm32mp157a-avenger96, stm32mp157a-dk1, stm32mp157a-ed1, stm32mp157a-ev1, stm32mp157c-dk2, stm32mp157c-ed1, stm32mp157c-ev1, stm32mp157d-dk1, stm32mp157d-ed1, stm32mp157f-dk2, stm32mp157f-ed1, stm32mp157f-ev1 ]

    steps:
      - uses: actions/checkout@v2
        with:
          path: stm32mp1-ubuntu
          
      - name: Install depends
        run: sudo apt-get install -y zip lzop lzma gettext libmpc-dev u-boot-tools libncurses5-dev pv gzip flex bison ncurses-base build-essential device-tree-compiler
          
      - name: Submodules init
        working-directory: ./stm32mp1-ubuntu
        run: git submodule init

      - name: Get U-boot & AT-F
        working-directory: ./stm32mp1-ubuntu
        run: |
          git submodule update --recursive --remote   u-boot
          git submodule update --recursive --remote   arm-trusted-firmware

      - name: Build U-boot and ARM trusted firmware
        working-directory: ./stm32mp1-ubuntu
        run: bash build-uboot.sh ${{ matrix.board }}

      - name: Get kernel 
        working-directory: ./stm32mp1-ubuntu
        run: git submodule update --recursive --remote   linux

      - name: Build kernel 
        env:
         HOSTNAME: Runner
         USER: GitHub
        working-directory: ./stm32mp1-ubuntu
        run: bash build-linux.sh

      - name: Get rootfs 
        working-directory: ./stm32mp1-ubuntu
        run: bash rootfs.sh

      - name: Make rootfs 
        working-directory: ./stm32mp1-ubuntu
        run: bash create-rootfs.sh ${{ matrix.board }} 

      - name: ZIP artifact
        run: |
          mkdir -p ./upload
          mv -v ${{runner.workspace}}/stm32mp1-ubuntu/stm32mp1-ubuntu/artifacts/*${{ matrix.conboardfig }}*.img ./upload/ubuntu-22.04-${{ matrix.board }}.img
          echo "login: ubuntu" > ./upload/login-pass.txt
          echo "password: root" >> ./upload/login-pass.txt

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ubuntu-22.04-${{ matrix.board }} (this is unzipped size)
          path: ./upload
